import { type RequestProps } from '../types/ffbe-api.js'

export const FFBE_REQUESTS = {
  GachaBoxNextRequest: {
    Name: 'GachaBoxNextRequest',
    Url: 'tULiKh5j',
    EncodeKey: 'U2Lm8vcS',
    RequestID: 'xa9uR3pI',
  },
  AllianceDeckEdit: {
    Name: 'AllianceDeckEdit',
    Url: '7gAGFC4I',
    EncodeKey: '2E3UinsJ',
    RequestID: 'P76LYXow',
  },
  SgSlotInfo: {
    Name: 'SgSlotInfo',
    Url: 'action',
    EncodeKey: 'gsRV5GaY',
    RequestID: 'uVswysHK',
  },
  SgSlot: {
    Name: 'SgSlot',
    Url: 'action',
    EncodeKey: 'vyLhq43j',
    RequestID: 'DW2yAFjB',
  },
  AllianceEntry: {
    Name: 'AllianceEntry',
    Url: 'EzfT0wX6',
    EncodeKey: 'zS4tPgi7',
    RequestID: 'HtR8XF4e',
  },
  AllianceUndercoverStrengthen: {
    Name: 'AllianceUndercoverStrengthen',
    Url: 'UR1OtKJS',
    EncodeKey: '75pZA8tv',
    RequestID: 'qj63QmHE',
  },
  ArchiveUpdate: {
    Name: 'ArchiveUpdate',
    Url: '2bCcKx0D',
    EncodeKey: 'IFLW9H4M',
    RequestID: 'cVTxW0K3',
  },
  BeastBoardPieceOpen: {
    Name: 'BeastBoardPieceOpen',
    Url: 'Y2Zvnad9',
    EncodeKey: '7uxYTm3k',
    RequestID: '0gk3Tfbz',
  },
  BeastMix: {
    Name: 'BeastMix',
    Url: '7vHqNPF0',
    EncodeKey: 'WfNSmy98',
    RequestID: 'C8X1KUpV',
  },
  BundlePurchase: {
    Name: 'BundlePurchase',
    Url: 'tPc64qmn',
    EncodeKey: 'NE3Pp4K8',
    RequestID: 'w6Z9a6tD',
  },
  BundleStatus: {
    Name: 'BundleStatus',
    Url: 'tPc64qmn',
    EncodeKey: 'PrSPuc8c',
    RequestID: 'uLXAMvCT',
  },
  CampaignTieup: {
    Name: 'CampaignTieup',
    Url: '2u30vqfY',
    EncodeKey: '72d5UTNC',
    RequestID: 'mI0Q2YhW',
  },
  ChallengeClear: {
    Name: 'ChallengeClear',
    Url: 'dEvLKchl',
    EncodeKey: 'UD5QCa2s',
    RequestID: 'D9xphQ8X',
  },
  ClsmEnd: {
    Name: 'ClsmEnd',
    Url: '7vHqNPF0',
    EncodeKey: '6aBHXGv4',
    RequestID: '3zgbapQ7',
  },
  ClsmEntry: {
    Name: 'ClsmEntry',
    Url: 'UmLwv56W',
    EncodeKey: '8bmHF3Cz',
    RequestID: '5g0vWZFq',
  },
  ClsmLottery: {
    Name: 'ClsmLottery',
    Url: '4uj3NhUQ',
    EncodeKey: 'pU62SkhJ',
    RequestID: 'Un16HuNI',
  },
  ClsmStart: {
    Name: 'ClsmStart',
    Url: 'rncR9js8',
    EncodeKey: 'wdSs23yW',
    RequestID: '4uCSA3ko',
  },
  CraftAdd: {
    Name: 'CraftAdd',
    Url: 'iQ7R4CFB',
    EncodeKey: 'qz0SG1Ay',
    RequestID: 'QkN1Sp64',
  },
  CraftCancel: {
    Name: 'CraftCancel',
    Url: '7WdDLIE4',
    EncodeKey: '68zcUF3E',
    RequestID: '79xDN1Mw',
  },
  CraftEnd: {
    Name: 'CraftEnd',
    Url: '9G7Vc8Ny',
    EncodeKey: 'yD97t8kB',
    RequestID: 'WIuvh09n',
  },
  CraftExe: {
    Name: 'CraftExe',
    Url: 'UyHLjV60',
    EncodeKey: 'ZbHEB15J',
    RequestID: 'PKDhIN34',
  },
  CraftStart: {
    Name: 'CraftStart',
    Url: 'w71MZ0Gg',
    EncodeKey: 'K92H8wkY',
    RequestID: 'Gr9zxXk5',
  },
  CreateUser: {
    Name: 'CreateUser',
    Url: '0FK8NJRX',
    EncodeKey: '73BUnZEr',
    RequestID: 'P6pTz4WA',
  },
  DailyDungeonSelect: {
    Name: 'DailyDungeonSelect',
    Url: '9LgmdR0v',
    EncodeKey: 'ioC6zqG1',
    RequestID: 'JyfxY2e0',
  },
  DailyQuestClaimAllReward: {
    Name: 'DailyQuestClaimAllReward',
    Url: 'Br9PwJ6A',
    EncodeKey: 'KHx6JdrT',
    RequestID: 'DCmya9WD',
  },
  DailyQuestClaimReward: {
    Name: 'DailyQuestClaimReward',
    Url: 'Br9PwJ6A',
    EncodeKey: 'jwYGF3sY',
    RequestID: 'Zy8fYJ5e',
  },
  DailyQuestShare: {
    Name: 'DailyQuestShare',
    Url: '3sTwRcpq',
    EncodeKey: 'PMyGMdUa',
    RequestID: '3sTwRcpq',
  },
  DailyQuestUpdate: {
    Name: 'DailyQuestUpdate',
    Url: 'QWDn5epF',
    EncodeKey: '9QtGVCWg',
    RequestID: '6QYd5Hym',
  },
  DmgRankEnd: {
    Name: 'DmgRankEnd',
    Url: 'zd5KJ3jn',
    EncodeKey: '7pGj8hSW',
    RequestID: 's98cw1WA',
  },
  DmgRankRetire: {
    Name: 'DmgRankRetire',
    Url: '8wdmR9yG',
    EncodeKey: '5fkWyeE6',
    RequestID: 'W3Z4VF1X',
  },
  DmgRankStart: {
    Name: 'DmgRankStart',
    Url: 'j37Vk5xe',
    EncodeKey: '1d5AP9p6',
    RequestID: '5P6ULvjg',
  },
  DungeonLiberation: {
    Name: 'DungeonLiberation',
    Url: '0vc6irBY',
    EncodeKey: '0xDA4Cr9',
    RequestID: 'nQMb2L4h',
  },
  DungeonResourceLoadMstList: {
    Name: 'DungeonResourceLoadMstList',
    Url: 'Sl8UgmP4',
    EncodeKey: '3PVu6ReZ',
    RequestID: 'jnw49dUq',
  },
  EquipGrowAbilityFix: {
    Name: 'EquipGrowAbilityFix',
    Url: 'CnPyXkUV',
    EncodeKey: '58dS0DZN',
    RequestID: 'k8ew94DN',
  },
  EquipGrowAbilitySelectResume: {
    Name: 'EquipGrowAbilitySelectResume',
    Url: 'Ke7YG3xW',
    EncodeKey: '7YxgkK1V',
    RequestID: '80R6BXUw',
  },
  EquipGrowEntry: {
    Name: 'EquipGrowEntry',
    Url: 'UiSOVXT2',
    EncodeKey: '6fTy3HRM',
    RequestID: 'U8F0Q25i',
  },
  ExchangeShop: {
    Name: 'ExchangeShop',
    Url: '1bf0HF4w',
    EncodeKey: 'qoRP87Fw',
    RequestID: 'I7fmVX3R',
  },
  ExploreEntry: {
    Name: 'ExploreEntry',
    Url: 'mr6DnTQV',
    EncodeKey: 'a4X1Q2Hm',
    RequestID: 'Tnkz60cb',
  },
  ExploreRetire: {
    Name: 'ExploreRetire',
    Url: 'Gv0BZr4X',
    EncodeKey: '3jTz0GIE',
    RequestID: 't8Yd2Pcy',
  },
  ExploreRewardGet: {
    Name: 'ExploreRewardGet',
    Url: 'RhznNjzo',
    EncodeKey: 'LaFmew85',
    RequestID: 'XG3CwM1N',
  },
  ExploreSetting: {
    Name: 'ExploreSetting',
    Url: 'O4JRsPZU',
    EncodeKey: 'i6M7o0cg',
    RequestID: 'f8Q0BJVX',
  },
  ExploreStart: {
    Name: 'ExploreStart',
    Url: '0PIk8qdm',
    EncodeKey: '0Xpfxg7U',
    RequestID: 'FR4ISN7P',
  },
  FacebookAddFriend: {
    Name: 'FacebookAddFriend',
    Url: 'NAW9vJnm',
    EncodeKey: '532vAYUy',
    RequestID: 'NAW9vJnm',
  },
  FacebookLogout: {
    Name: 'FacebookLogout',
    Url: 'xHTo4BZp',
    EncodeKey: 'wwHxtAy6',
    RequestID: 'xHTo4BZp',
  },
  FacebookRewardClaim: {
    Name: 'FacebookRewardClaim',
    Url: '47R9pLGq',
    EncodeKey: 'Rja82ZUK',
    RequestID: '47R9pLGq',
  },
  FacebookRewardList: {
    Name: 'FacebookRewardList',
    Url: '8YZsGLED',
    EncodeKey: '85YBRzZg',
    RequestID: '8YZsGLED',
  },
  FriendAgree: {
    Name: 'FriendAgree',
    Url: '1DYp5Nqm',
    EncodeKey: '9FjK0zM3',
    RequestID: 'kx13SLUY',
  },
  FriendDelete: {
    Name: 'FriendDelete',
    Url: '8R4fQbYh',
    EncodeKey: 'd0VP5ia6',
    RequestID: 'a2d6omAy',
  },
  FriendDetail: {
    Name: 'FriendDetail',
    Url: 'QBiJEyUt',
    EncodeKey: 'aKvkU6Y4',
    RequestID: '7kG0JAvE',
  },
  FriendFavorite: {
    Name: 'FriendFavorite',
    Url: '8IYSJ5H1',
    EncodeKey: '3EBXbj1d',
    RequestID: '1oE3Fwn4',
  },
  FriendList: {
    Name: 'FriendList',
    Url: 'p3hwqW5U',
    EncodeKey: '1iV2oN9r',
    RequestID: 'u7Id4bMg',
  },
  FriendRefuse: {
    Name: 'FriendRefuse',
    Url: 'Vw0a4I3i',
    EncodeKey: 'RYdX9h2A',
    RequestID: '1nbWRV9w',
  },
  Friend: {
    Name: 'Friend',
    Url: '8drhF2mG',
    EncodeKey: '6WAkj0IH',
    RequestID: 'j0A5vQd8',
  },
  FriendSearch: {
    Name: 'FriendSearch',
    Url: '6Y1jM3Wp',
    EncodeKey: 'VCL5oj6u',
    RequestID: '3siZRSU4',
  },
  FriendSuggest: {
    Name: 'FriendSuggest',
    Url: '6TCn0BFh',
    EncodeKey: 'j2P3uqRC',
    RequestID: 'iAs67PhJ',
  },
  GachaEntry: {
    Name: 'GachaEntry',
    Url: 'tUJxSQz7',
    EncodeKey: '39cFjtId',
    RequestID: 'rj6dxU9w',
  },
  GachaExe: {
    Name: 'GachaExe',
    Url: 'oC30VTFp',
    EncodeKey: 'oaEJ9y1Z',
    RequestID: '9fVIioy1',
  },
  GachaInfo: {
    Name: 'GachaInfo',
    Url: '3nhWq25K',
    EncodeKey: 'VA8QR57X',
    RequestID: 'UNP1GR5n',
  },
  GachaSelectExe: {
    Name: 'GachaSelectExe',
    Url: 'eB0VYGMt',
    EncodeKey: 'BuJqHc41',
    RequestID: 'xio14KrL',
  },
  GameSetting: {
    Name: 'GameSetting',
    Url: 'OTX6Fmvu',
    EncodeKey: '4foXVwWd',
    RequestID: 'OTX6Fmvu',
  },
  GetBackgroundDownloadInfo: {
    Name: 'GetBackgroundDownloadInfo',
    Url: 'action',
    EncodeKey: 'Z1krd75o',
    RequestID: 'lEHBdOEf',
  },
  GetReinforcementInfo: {
    Name: 'GetReinforcementInfo',
    Url: 'hXMoLwgE',
    EncodeKey: '87khNMou',
    RequestID: 'AJhnI37s',
  },
  GetTitleInfo: {
    Name: 'GetTitleInfo',
    Url: 'BbIeq31M',
    EncodeKey: 'Mw56RNZ2',
    RequestID: 'ocP3A1FI',
  },
  GetUserInfo3: {
    Name: 'GetUserInfo3',
    Url: 'lZXr14iy',
    EncodeKey: '0Dn4hbWC',
    RequestID: '4rjw5pnv',
  },
  GetUserInfo2: {
    Name: 'GetUserInfo2',
    Url: '7KZ4Wvuw',
    EncodeKey: '7VNRi6Dk',
    RequestID: '2eK5Vkr8',
  },
  GetUserInfo: {
    Name: 'GetUserInfo',
    Url: 'u7sHDCg4',
    EncodeKey: 'rcsq2eG7',
    RequestID: 'X07iYtp5',
  },
  GiftUpdate: {
    Name: 'GiftUpdate',
    Url: 'noN8I0UK',
    EncodeKey: 'xLEtf78b',
    RequestID: '9KN5rcwj',
  },
  GooglePromotionReward: {
    Name: 'GooglePromotionReward',
    Url: 'jSxaKcr0',
    EncodeKey: 'F7AMb1u2',
    RequestID: '6PDhpa5T',
  },
  GrandMissionEntry: {
    Name: 'GrandMissionEntry',
    Url: '8DermCsY',
    EncodeKey: 'Uey5jW2G',
    RequestID: 'MTf2j9aK',
  },
  Initialize: {
    Name: 'Initialize',
    Url: 'fSG1eXI9',
    EncodeKey: 'rVG09Xnt',
    RequestID: '75fYdNxq',
  },
  IsNeedValidate: {
    Name: 'IsNeedValidate',
    Url: 'gk3Wtr8A',
    EncodeKey: 'djhiU6x8',
    RequestID: 'er5xMIj6',
  },
  ItemBuy: {
    Name: 'ItemBuy',
    Url: 'oQrAys71',
    EncodeKey: 'InN5PUR0',
    RequestID: 'sxK2HG6T',
  },
  ItemCarryEdit: {
    Name: 'ItemCarryEdit',
    Url: '8BE6tJbf',
    EncodeKey: '04opy1kf',
    RequestID: 'UM7hA0Zd',
  },
  ItemSell: {
    Name: 'ItemSell',
    Url: 'hQRf8D6r',
    EncodeKey: 'E8H3UerF',
    RequestID: 'd9Si7TYm',
  },
  LoginBonus: {
    Name: 'LoginBonus',
    Url: 'iP9ogKy6',
    EncodeKey: 'Vi6vd9zG',
    RequestID: 'vw9RP3i4',
  },
  MailList: {
    Name: 'MailList',
    Url: 'u3E8hpad',
    EncodeKey: '7kgsrGQ1',
    RequestID: 'KQHpi0D7',
  },
  MailReceipt: {
    Name: 'MailReceipt',
    Url: 'M2fHBe9d',
    EncodeKey: 'P2YFr7N9',
    RequestID: 'XK7efER9',
  },
  MedalExchange: {
    Name: 'MedalExchange',
    Url: '0X8Fpjhb',
    EncodeKey: 'dCja1E54',
    RequestID: 'LiM9Had2',
  },
  MissionBreak: {
    Name: 'MissionBreak',
    Url: 'P4oIeVf0',
    EncodeKey: 'Z2oPiE6p',
    RequestID: '17LFJD0b',
  },
  MissionContinue: {
    Name: 'MissionContinue',
    Url: 'ZzCXI6E7',
    EncodeKey: '34n2iv7z',
    RequestID: 'LuCN4tU5',
  },
  MissionContinueRetire: {
    Name: 'MissionContinueRetire',
    Url: 'cQU1D9Nx',
    EncodeKey: 'F1QRxT5m',
    RequestID: 'V3CiWT0r',
  },
  MissionEnd: {
    Name: 'MissionEnd',
    Url: '0ydjM5sU',
    EncodeKey: '1tg0Lsqj',
    RequestID: 'x5Unqg2d',
  },
  MissionReStart: {
    Name: 'MissionReStart',
    Url: 'r5vfM1Y3',
    EncodeKey: 'Vw6bP0rN',
    RequestID: 'GfI4LaU3',
  },
  MissionRetire: {
    Name: 'MissionRetire',
    Url: 'gbZ64SQ2',
    EncodeKey: 'oUh1grm8',
    RequestID: 'v51PM7wj',
  },
  MissionStart: {
    Name: 'MissionStart',
    Url: '63VqtzbQ',
    EncodeKey: 'i48eAVL6',
    RequestID: '29JRaDbd',
  },
  MissionSwitchUpdate: {
    Name: 'MissionSwitchUpdate',
    Url: '1Xz8kJLr',
    EncodeKey: 'bZezA63a',
    RequestID: 'Tvq54dx6',
  },
  MissionUpdate: {
    Name: 'MissionUpdate',
    Url: 'fRDUy3E2',
    EncodeKey: 'Nq9uKGP7',
    RequestID: 'j5JHKq6S',
  },
  MissionWaveReStart: {
    Name: 'MissionWaveReStart',
    Url: '8m7KNezI',
    EncodeKey: 'M3bYZoU5',
    RequestID: 'e9RP8Cto',
  },
  MissionWaveStart: {
    Name: 'MissionWaveStart',
    Url: 'Mn15zmDZ',
    EncodeKey: 'd2mqJ6pT',
    RequestID: 'BSq28mwY',
  },
  MyCardInitialize: {
    Name: 'MyCardInitialize',
    Url: 'd6f9LSI7',
    EncodeKey: 'q54ajlRb',
    RequestID: 'BruItbuW',
  },
  NoticeReadUpdate: {
    Name: 'NoticeReadUpdate',
    Url: 'j6kSWR3q',
    EncodeKey: 'iLdaq6j2',
    RequestID: 'pC3a2JWU',
  },
  NoticeUpdate: {
    Name: 'NoticeUpdate',
    Url: 'TqtzK84R',
    EncodeKey: '9t68YyjT',
    RequestID: 'CQ4jTm2F',
  },
  OptionUpdate: {
    Name: 'OptionUpdate',
    Url: '0Xh2ri5E',
    EncodeKey: 'B9mAa7rp',
    RequestID: 'otgXV79T',
  },
  PartyDeckEdit: {
    Name: 'PartyDeckEdit',
    Url: '6xkK4eDG',
    EncodeKey: '34qFNPf7',
    RequestID: 'TS5Dx9aZ',
  },
  PartyRegisterSlotLoad: {
    Name: 'PartyRegisterSlotLoad',
    Url: '2y4BVhyj',
    EncodeKey: '7zcaE16T',
    RequestID: 'Q7jV6pno',
  },
  PartyRegisterSlotSave: {
    Name: 'PartyRegisterSlotSave',
    Url: 'QjDQEMYc',
    EncodeKey: '0S9Uzr42',
    RequestID: 'CE98eghN',
  },
  PartyRegisterSlotUpdate: {
    Name: 'PartyRegisterSlotUpdate',
    Url: 'HgSTAzd2',
    EncodeKey: 'CpZH8rY0',
    RequestID: 'RQ5BjDE0',
  },
  PlaybackMissionStart: {
    Name: 'PlaybackMissionStart',
    Url: 'zm2ip59f',
    EncodeKey: 'YC20v1Uj',
    RequestID: '1YnQM4iB',
  },
  PlaybackMissionWaveStart: {
    Name: 'PlaybackMissionWaveStart',
    Url: 'scyPYa81',
    EncodeKey: 'NdkX15vE',
    RequestID: '1BpXP3Fs',
  },
  PlayerEmblemEntry: {
    Name: 'PlayerEmblemEntry',
    Url: 'huKNdci6',
    EncodeKey: 'F7A2MJoE',
    RequestID: 'Z7J9H6TK',
  },
  PlayerEmblemSetting: {
    Name: 'PlayerEmblemSetting',
    Url: 'cswGxj8F',
    EncodeKey: '76kGLIgN',
    RequestID: '19YwqU2T',
  },
  PurchaseCancel: {
    Name: 'PurchaseCancel',
    Url: 'y71uBCER',
    EncodeKey: 'Z1mojg9a',
    RequestID: 'L7K0ezU2',
  },
  PurchaseCurrentState: {
    Name: 'PurchaseCurrentState',
    Url: 'bAR4k7Qd',
    EncodeKey: 'X9k5vFdu',
    RequestID: '9mM3eXgi',
  },
  PurchaseFailed: {
    Name: 'PurchaseFailed',
    Url: '2TCis0R6',
    EncodeKey: 'sW0vf3ZM',
    RequestID: 'jSe80Gx7',
  },
  PurchaseGiveUp: {
    Name: 'PurchaseGiveUp',
    Url: 'C2w0f3go',
    EncodeKey: 'xoZ62QWy',
    RequestID: 'BFf1nwh6',
  },
  PurchaseHold: {
    Name: 'PurchaseHold',
    Url: 'dCxtMZ27',
    EncodeKey: '5Mwfq90Z',
    RequestID: '79EVRjeM',
  },
  PurchaseList: {
    Name: 'PurchaseList',
    Url: 'YqZ6Qc1z',
    EncodeKey: 'X3Csghu0',
    RequestID: 'BT28S96F',
  },
  PurchaseSetting: {
    Name: 'PurchaseSetting',
    Url: '9hUtW0F8',
    EncodeKey: 'ePFcMX53',
    RequestID: 'QkwU4aD9',
  },
  PurchaseSettlement: {
    Name: 'PurchaseSettlement',
    Url: 'yt82BRwk',
    EncodeKey: 'jmh7xID8',
    RequestID: 'JsFd4b7j',
  },
  PurchaseStart: {
    Name: 'PurchaseStart',
    Url: 'tPc64qmn',
    EncodeKey: '9Kf4gYvm',
    RequestID: 'qAUzP3R6',
  },
  RateAppReward: {
    Name: 'RateAppReward',
    Url: 'L0OsxMaT',
    EncodeKey: 'm1pPBwC3',
    RequestID: 'L0OsxMaT',
  },
  RbBoardPieceOpen: {
    Name: 'RbBoardPieceOpen',
    Url: 'iXKfI4v1',
    EncodeKey: 'g68FW4k1',
    RequestID: 'hqzU9Qc5',
  },
  RbEnd: {
    Name: 'RbEnd',
    Url: 'e8AHNiT7',
    EncodeKey: 'MVA3Te2i',
    RequestID: 'os4k7C0b',
  },
  RbEntry: {
    Name: 'RbEntry',
    Url: '30inL7I6',
    EncodeKey: 'EA5amS29',
    RequestID: 'f8kXGWy0',
  },
  RbMatching: {
    Name: 'RbMatching',
    Url: 'mn5cHaJ0',
    EncodeKey: '4GSMn0qb',
    RequestID: 'DgG4Cy0F',
  },
  RbRanking: {
    Name: 'RbRanking',
    Url: '3fd8y7W1',
    EncodeKey: 'SR6PoLM3',
    RequestID: 'kcW85SfU',
  },
  RbReStart: {
    Name: 'RbReStart',
    Url: 'DQ49vsGL',
    EncodeKey: 'PRzAL3V2',
    RequestID: '6ZNY3zAm',
  },
  RbStart: {
    Name: 'RbStart',
    Url: 'dR20sWwE',
    EncodeKey: 'P1w8BKLI',
    RequestID: 'eHY7X8Nn',
  },
  ReinforcementSetting: {
    Name: 'ReinforcementSetting',
    Url: 'I1g4ezbP',
    EncodeKey: 'jUreV31B',
    RequestID: 'ZSq2y7EX',
  },
  ResourceAllDownload: {
    Name: 'ResourceAllDownload',
    Url: 'Vtx9kFg0',
    EncodeKey: 'fL07ojUc',
    RequestID: 'i0d5n1Dp',
  },
  RmDungeonEnd: {
    Name: 'RmDungeonEnd',
    Url: 'CH9fWn8K',
    EncodeKey: 'dEnsQ75t',
    RequestID: 'WaPC2T6i',
  },
  RmDungeonStart: {
    Name: 'RmDungeonStart',
    Url: 'NC8Ie07P',
    EncodeKey: 'A7V1zkyc',
    RequestID: 'R5mWbQ3M',
  },
  RmEnd: {
    Name: 'RmEnd',
    Url: 'I9p3n48A',
    EncodeKey: 'FX5L3Sfv',
    RequestID: 'fyp10Rrc',
  },
  RmEntry: {
    Name: 'RmEntry',
    Url: 'fBn58ApV',
    EncodeKey: 'p2tqP7Ng',
    RequestID: 'wx5sg9ye',
  },
  RmRestart: {
    Name: 'RmRestart',
    Url: 'NC8Ie07P',
    EncodeKey: 'R1VjnNx0',
    RequestID: 'yh21MTaG',
  },
  RmRetire: {
    Name: 'RmRetire',
    Url: 'fBn58ApV',
    EncodeKey: 'T4Undsr6',
    RequestID: 'e0R3iDm1',
  },
  RmStart: {
    Name: 'RmStart',
    Url: '8BJSL7g0',
    EncodeKey: 'iu67waph',
    RequestID: '7FyJS3Zn',
  },
  RoutineEventUpdate: {
    Name: 'RoutineEventUpdate',
    Url: 'WCK5tvr0',
    EncodeKey: 'V0TGwId5',
    RequestID: '4kA1Ne05',
  },
  RoutineGachaUpdate: {
    Name: 'RoutineGachaUpdate',
    Url: 'qS0YW57G',
    EncodeKey: 'Q6ZGJj0h',
    RequestID: 't60dQP49',
  },
  RoutineHomeUpdate: {
    Name: 'RoutineHomeUpdate',
    Url: '1YWTzU9h',
    EncodeKey: 'aw0syG7H',
    RequestID: 'Daud71Hn',
  },
  RoutineRaidMenuUpdate: {
    Name: 'RoutineRaidMenuUpdate',
    Url: 'Sv85kcPQ',
    EncodeKey: 'z80swWd9',
    RequestID: 'g0BjrU5D',
  },
  RoutineWorldUpdate: {
    Name: 'RoutineWorldUpdate',
    Url: 'oR1psQ5B',
    EncodeKey: 'XDIL4E7j',
    RequestID: '6H1R9WID',
  },
  Sacrifice: {
    Name: 'Sacrifice',
    Url: 'QBiJEyUt',
    EncodeKey: 'U80FYThX',
    RequestID: '7tWdn9zH',
  },
  SearchGetItemInfo: {
    Name: 'SearchGetItemInfo',
    Url: 'e4Gjkf0x',
    EncodeKey: 'vK2V8mZM',
    RequestID: '0D9mpGUR',
  },
  sgAdsGachaMilestone: {
    Name: 'sgAdsGachaMilestone',
    Url: 'PkSzb2TM',
    EncodeKey: 'Jp4Fz3qb',
    RequestID: 'PkSzb2TM',
  },
  sgComebackQuestClaimReward: {
    Name: 'sgComebackQuestClaimReward',
    Url: 'I7RzrQ3J',
    EncodeKey: '4NO3PIyU',
    RequestID: '1IOdaWOW',
  },
  sgExpdAccelerate: {
    Name: 'sgExpdAccelerate',
    Url: 'Ik142Ff6',
    EncodeKey: 'd3D4l8b4',
    RequestID: 'Ik142Ff6',
  },
  sgExpdEnd: {
    Name: 'sgExpdEnd',
    Url: '2pe3Xa8bpG',
    EncodeKey: 'cjHumZ2Jkt',
    RequestID: '2pe3Xa8bpG',
  },
  sgExpdMileStoneClaim: {
    Name: 'sgExpdMileStoneClaim',
    Url: 'r4A791RF',
    EncodeKey: 't04N07LQ',
    RequestID: 'r4A791RF',
  },
  sgExpdQuestInfo: {
    Name: 'sgExpdQuestInfo',
    Url: 'hW0804Q9',
    EncodeKey: '4Bn7d973',
    RequestID: 'hW0804Q9',
  },
  sgExpdQuestRefresh: {
    Name: 'sgExpdQuestRefresh',
    Url: 'vTgYyHM6lC',
    EncodeKey: 'vceNlSf3gn',
    RequestID: 'vTgYyHM6lC',
  },
  sgExpdQuestStart: {
    Name: 'sgExpdQuestStart',
    Url: 'I8uq68c3',
    EncodeKey: '60Os29Mg',
    RequestID: 'I8uq68c3',
  },
  sgExpdRecall: {
    Name: 'sgExpdRecall',
    Url: '0Fb87D0F',
    EncodeKey: '9J02K0lX',
    RequestID: '0Fb87D0F',
  },
  sgHiddenSkillUpgrade: {
    Name: 'sgHiddenSkillUpgrade',
    Url: 'qxUUaS8s',
    EncodeKey: 'rXDvnsv8',
    RequestID: 'qxUUaS8s',
  },
  sgHomeMarqueeInfo: {
    Name: 'sgHomeMarqueeInfo',
    Url: 'PBSP9qn5',
    EncodeKey: 'd3GDS9X8',
    RequestID: 'PBSP9qn5',
  },
  sgMissionUnlock: {
    Name: 'sgMissionUnlock',
    Url: 'LJhqu0x6',
    EncodeKey: 'ZcBV06K4',
    RequestID: 'LJhqu0x6',
  },
  sgOfferwallInfo: {
    Name: 'sgOfferwallInfo',
    Url: 'NmNB96p8',
    EncodeKey: 'QgNR0HvE',
    RequestID: 'uO1w9ggv',
  },
  sgUserExtraChallengeInfo: {
    Name: 'sgUserExtraChallengeInfo',
    Url: 'zgry2aNV',
    EncodeKey: 'Qu6RHqbb',
    RequestID: 'dzU2t3HA',
  },
  ShopExchangeItemList: {
    Name: 'ShopExchangeItemList',
    Url: '7KJjJiIh',
    EncodeKey: 'h69WSu02',
    RequestID: 'syKz34cE',
  },
  ShopExchangeItem: {
    Name: 'ShopExchangeItem',
    Url: 'qhP5wSXV',
    EncodeKey: 'vaDW85R2',
    RequestID: 'xD5b6PqQ',
  },
  ShopExchangeUnit: {
    Name: 'ShopExchangeUnit',
    Url: 'lnXYChmF',
    EncodeKey: 'x6rSuK0J',
    RequestID: 'Vgi7j68T',
  },
  ShopUse: {
    Name: 'ShopUse',
    Url: 'w76ThDMm',
    EncodeKey: 'ZT0Ua4wL',
    RequestID: '73SD2aMR',
  },
  SignInCheck: {
    Name: 'SignInCheck',
    Url: 'Qfpa24mZ',
    EncodeKey: 'F83wNKFt',
    RequestID: 'ufKRrNc7',
  },
  SignIn: {
    Name: 'SignIn',
    Url: '8DRAiBXE',
    EncodeKey: 'g8iv4P8I',
    RequestID: 'FckReppg',
  },
  SignOut: {
    Name: 'SignOut',
    Url: 'KwChAfkX',
    EncodeKey: 'UtE1qMv3',
    RequestID: 'o96pHAp3',
  },
  SpChallengeEntry: {
    Name: 'SpChallengeEntry',
    Url: '8DermCsY',
    EncodeKey: 'Uey5jW2G',
    RequestID: 'MTf2j9aK',
  },
  SpChallengeRewardGet: {
    Name: 'SpChallengeRewardGet',
    Url: '9inGHyqC',
    EncodeKey: 'mG25PIUn',
    RequestID: '2G7ZVs4A',
  },
  StrongBoxOpen: {
    Name: 'StrongBoxOpen',
    Url: '48ktHf13',
    EncodeKey: 'sgc30nRh',
    RequestID: 'PIv7u8jU',
  },
  SublimationSkill: {
    Name: 'SublimationSkill',
    Url: 'xG3jBbw5',
    EncodeKey: '97Uvrdz3',
    RequestID: 's48Qzvhd',
  },
  TowerEnd: {
    Name: 'TowerEnd',
    Url: 'TZXbYd9b',
    EncodeKey: 'kzFy73L9',
    RequestID: 'fBN47X2b',
  },
  TowerEntry: {
    Name: 'TowerEntry',
    Url: 'scI7HnwD',
    EncodeKey: 'L9d1gYAm',
    RequestID: 'VfEh2wD0',
  },
  TowerRestart: {
    Name: 'TowerRestart',
    Url: 'iqxK7alu',
    EncodeKey: '04HMuYV1',
    RequestID: '9Z3jCWfF',
  },
  TowerRetire: {
    Name: 'TowerRetire',
    Url: 'sn4mo4gN',
    EncodeKey: '5dqrT8Mi',
    RequestID: 'MTuX7ai2',
  },
  TowerStart: {
    Name: 'TowerStart',
    Url: '1ch0bfGj',
    EncodeKey: 'M3dCmDW8',
    RequestID: 'dZA90j5s',
  },
  TownIn: {
    Name: 'TownIn',
    Url: 'isHfQm09',
    EncodeKey: 'JI8zU5rC',
    RequestID: '8EYGrg76',
  },
  TownOut: {
    Name: 'TownOut',
    Url: '0EF3JPjL',
    EncodeKey: 'Kc2PXd9D',
    RequestID: 'sJcMPy04',
  },
  TownUpdate: {
    Name: 'TownUpdate',
    Url: '0ZJzH2qY',
    EncodeKey: '37nH21zE',
    RequestID: 'G1hQM8Dr',
  },
  TransferCodeCheck: {
    Name: 'TransferCodeCheck',
    Url: 'C9LoeYJ8',
    EncodeKey: 'c5aNjK9J',
    RequestID: 'CY89mIdz',
  },
  TransferCodeIssue: {
    Name: 'TransferCodeIssue',
    Url: 'hF0yCKc1',
    EncodeKey: 'T0y6ij47',
    RequestID: 'crzI2bA5',
  },
  Transfer: {
    Name: 'Transfer',
    Url: 'v6Jba7pX',
    EncodeKey: 'C6eHo3wU',
    RequestID: 'oE5fmZN9',
  },
  TrophyReward: {
    Name: 'TrophyReward',
    Url: '05vJDxg9',
    EncodeKey: '2o7kErn1',
    RequestID: 'wukWY4t2',
  },
  UltimaniaCodeIssue: {
    Name: 'UltimaniaCodeIssue',
    Url: '2D3yLWcW',
    EncodeKey: '4ouG6AjK',
    RequestID: 'D1gXmV3L',
  },
  UnitClassUp: {
    Name: 'UnitClassUp',
    Url: '8z4Z0DUY',
    EncodeKey: 'L2sTK0GM',
    RequestID: 'zf49XKg8',
  },
  UnitEquip: {
    Name: 'UnitEquip',
    Url: 'nIk9z5pT',
    EncodeKey: '45VZgFYv',
    RequestID: 'pB3st6Tg',
  },
  UnitFavorite: {
    Name: 'UnitFavorite',
    Url: 'sqeRg12M',
    EncodeKey: 'w9mWkGX0',
    RequestID: 'tBDi10Ay',
  },
  UnitMix: {
    Name: 'UnitMix',
    Url: '6aLHwhJ8',
    EncodeKey: '4zCuj2hK',
    RequestID: 'UiSC9y8R',
  },
  UnitSell: {
    Name: 'UnitSell',
    Url: '0qmzs2gA',
    EncodeKey: 'DJ43wmds',
    RequestID: '9itzg1jc',
  },
  UpdateSwitchInfo: {
    Name: 'UpdateSwitchInfo',
    Url: 'SqoB3a1T',
    EncodeKey: '4Z5UNaIW',
    RequestID: 'mRPo5n2j',
  },
  UpdateUserInfo: {
    Name: 'UpdateUserInfo',
    Url: 'v3RD1CUB',
    EncodeKey: '6v5ykfpr',
    RequestID: 'ey8mupb4',
  },
  ParadeEntry: {
    Name: 'ParadeEntry',
    Url: '9i4b61rU',
    EncodeKey: 'kF7Z5vCK',
    RequestID: 'Q46YTgWo',
  },
  ParadeMissionEnd: {
    Name: 'ParadeMissionEnd',
    Url: 'hC8r9p81',
    EncodeKey: 'Pv08w12y',
    RequestID: '4cACW7y3',
  },
  VariableStoreCheck: {
    Name: 'VariableStoreCheck',
    Url: 'Nhn93ukW',
    EncodeKey: 'Hi0FJU3c',
    RequestID: 'i0woEP4B',
  },
} as const satisfies Record<string, RequestProps>

export type FFBE_REQUESTS_NAME = keyof typeof FFBE_REQUESTS
